function ask(text){var v=String(text||byId('chatInput').value||'').trim();if(!v)return;state.chat.push({role:'user',text:v});state.chat.push({role:'ai',text:reply(v)});byId('chatInput').value='';safeSave();renderChat();setTimeout(function(){try{window.scrollTo(0,document.body.scrollHeight)}catch(e){}},30)}
function saveIdea(){var x=idea();state.memories.push({id:uid(),text:x,type:'Ideia',created:Date.now()});updateProfile();unlockAchievements();safeSave();render();toast('Ideia salva')}
function go(p){document.querySelectorAll('.page').forEach(function(x){x.className='page'});byId('page-'+p).className='page active';document.querySelectorAll('.nav button').forEach(function(x){x.className=x.getAttribute('data-page')===p?'active':''});try{window.scrollTo(0,0)}catch(e){}}
function saveName(){var n=clean(byId('nameInput').value);if(!n){toast('Digite seu nome');return}n=n.charAt(0).toUpperCase()+n.slice(1);state.name=n;safeSave();closeModal('nameModal');render();toast('Prazer, '+n+'!')}
function processInbox(){var lines=byId('inboxText').value.split(/\n+/).map(function(x){return x.trim()}).filter(Boolean);if(!lines.length){toast('Escreva pelo menos uma coisa');return}var counts={Tarefa:0,Ideia:0,Projeto:0,Memória:0,Pensamento:0};lines.forEach(function(line){var t=classify(line);counts[t]=(counts[t]||0)+1;if(t==='Tarefa')state.tasks.push({id:uid(),text:line,done:false,created:Date.now(),priority:'normal'});else{state.memories.push({id:uid(),text:line,type:t,created:Date.now()});if(t==='Projeto')maybeCreateProjectFromMemory(line)}});byId('inboxText').value='';closeModal('inboxModal');updateProfile();unlockAchievements();safeSave();render();var summary=Object.keys(counts).filter(function(k){return counts[k]}).map(function(k){return counts[k]+' '+k.toLowerCase()+(counts[k]>1?'s':'')}).join(', ');toast('Organizado: '+summary)}
function analyzeDecision(){var q=byId('decisionQuestion').value.trim(),opts=byId('decisionOptions').value.split(',').map(function(x){return x.trim()}).filter(Boolean);if(!q||opts.length<2){toast('Informe a decisão e pelo menos 2 opções');return}var th=themes(5).map(function(x){return x[0]}),html='<div class="decisionBox"><h3>'+esc(q)+'</h3>';opts.forEach(function(o,i){var related=th.filter(function(t){return norm(o).indexOf(t)>=0||norm(q).indexOf(t)>=0});var pro=related.length?'Conecta com temas que já aparecem no seu contexto: '+related.join(', ')+'.':'É uma opção nova, sem muito histórico seu ainda.';var risk=i===0?'Evite escolher só por familiaridade.':'Compare o esforço real necessário para testar.';html+='<p><b>'+esc(o)+'</b><br>Pró: '+esc(pro)+'<br>Risco: '+esc(risk)+'</p>'});html+='<p><b>Pergunta-chave:</b> qual opção você consegue testar em pequena escala primeiro, sem compromisso irreversível?</p></div>';byId('decisionResult').innerHTML=html}
function prioritizeTasks(){var themeMap=themeCounts();state.tasks.forEach(function(t){if(t.done)return;var score=0;words(t.text).forEach(function(w){score+=(themeMap[w]||0)});t.priority=score>=4?'high':'normal'});safeSave();renderTasks();toast('Prioridades recalculadas')}
function beginFocus(){var g=byId('focusGoalInput').value.trim();if(!g){toast('Defina o objetivo');return}currentFocusGoal=g;byId('focusGoalInput').value='';closeModal('focusModal');seconds=1500;running=true;byId('focusObjective').textContent=currentFocusGoal;byId('startFocus').textContent='Pausar';if(timer)clearInterval(timer);timer=setInterval(tick,1000);drawClock()}
function tick(){if(seconds>0){seconds--;drawClock()}else{if(timer)clearInterval(timer);timer=null;running=false;seconds=0;drawClock();byId('startFocus').textContent='Nova sessão';byId('focusEndText').textContent='Objetivo: '+currentFocusGoal;openModal('focusEndModal')}}
function drawClock(){var m=Math.floor(seconds/60),s=seconds%60;byId('clock').textContent=(m<10?'0':'')+m+':'+(s<10?'0':'')+s}
function finishFocus(result){state.focusSessions.push({id:uid(),goal:currentFocusGoal,result:result,endedAt:Date.now()});currentFocusGoal='';seconds=1500;drawClock();byId('focusObjective').textContent='Nenhum objetivo definido';closeModal('focusEndModal');updateProfile();unlockAchievements();safeSave();render();toast('Sessão registrada')}
function renderProfile(){updateProfile();var topics=state.profile.topics||[],strengths=state.profile.strengths||[];byId('profileContent').innerHTML='<div class="profileBlock"><h3>Assuntos recorrentes</h3>'+(topics.length?topics.map(function(x){return '<span class="profileTag">'+esc(x)+'</span>'}).join(''):'<span class="sub">Ainda não há dados suficientes.</span>')+'</div><div class="profileBlock"><h3>Onde você mais conclui coisas</h3>'+(strengths.length?strengths.map(function(x){return '<span class="profileTag">'+esc(x)+'</span>'}).join(''):'<span class="sub">Ainda aprendendo.</span>')+'</div><div class="profileBlock"><h3>Atividade</h3><p class="sub">'+(state.profile.captureCount||0)+' itens capturados · '+(state.profile.completedTasks||0)+' tarefas concluídas · '+(state.profile.focusSessions||0)+' sessões de foco · '+(state.profile.projectCount||0)+' projetos</p></div>'}
