function itemHtml(m){return '<div class="item"><div class="itemTop"><b>'+esc(m.type||'Memória')+'</b><button class="tiny" data-delmem="'+esc(m.id)+'">Excluir</button></div><p>'+esc(m.text)+'</p></div>'}
function taskHtml(t){return '<div class="item task '+(t.done?'done':'')+'"><button class="check" data-toggle="'+esc(t.id)+'">✓</button><div style="flex:1"><div class="itemTop"><b>'+(t.priority==='high'?'Prioridade alta':'Tarefa')+'</b><button class="tiny" data-deltask="'+esc(t.id)+'">Excluir</button></div><p>'+esc(t.text)+'</p><div class="minirow">'+(!t.done?'<button class="tiny" data-plan="'+esc(t.id)+'">✦ Quebrar em passos</button>':'')+'</div></div></div>'}
function renderBrief(){var old=resurfaceMemory();var extra=old?'<div class="minirow"><button class="tiny" data-resurface="'+esc(old.id)+'">⌁ Rever memória antiga</button></div>':'';byId('brief').innerHTML='<div class="briefTop"><div class="ai">✦</div><div><h3>'+(state.name?'Seu panorama, '+esc(state.name):'Seu panorama agora')+'</h3><p>'+esc(buildBrief())+'</p><div class="minirow"><button class="tiny" id="briefIdea">💡 Gerar ideia</button><button class="tiny" id="briefNext">✓ Próxima ação</button><button class="tiny" id="briefReview">🧭 Revisar dia</button></div>'+extra+'</div></div>'}
function renderAttention(){var list=attentionItems();byId('attentionList').innerHTML=list.map(function(a){return '<div class="item '+a.kind+'"><div class="itemTop"><b>'+esc(a.title)+'</b><span class="time">Henna</span></div><p>'+esc(a.text)+'</p>'+(a.theme?'<div class="minirow"><button class="tiny" data-makeproject="'+esc(a.theme)+'">Transformar em projeto</button></div>':'')+'</div>'}).join('')}
function renderConnections(){var list=connectionItems();byId('connectionsList').innerHTML=list.length?list.map(function(c){return '<div class="item connectionStrong"><div class="itemTop"><b>✨ '+esc(c.title)+'</b><span class="time">Conexão</span></div><p>'+esc(c.text)+'</p>'+(c.theme?'<div class="minirow"><button class="tiny" data-makeproject="'+esc(c.theme)+'">Criar projeto</button><button class="tiny" data-searchtheme="'+esc(c.theme)+'">Ver memórias</button></div>':'')+'</div>'}).join(''):'<div class="empty">As conexões aparecem quando a Henna percebe temas repetidos nas suas memórias e tarefas.</div>'}
function renderProjects(){var list=state.projects.filter(function(p){return !p.archived});byId('projectsList').innerHTML=list.length?list.map(function(p){var n=projectStats(p),pct=Math.min(100,20+n*12);return '<div class="item projectCard"><div class="itemTop"><b>🗺️ '+esc(p.name)+'</b><button class="tiny" data-archiveproject="'+esc(p.id)+'">Arquivar</button></div><p>'+esc(p.goal||'Projeto em construção.')+'</p><div class="projectMeta"><span>'+n+' itens relacionados</span><span>'+(p.auto?'detectado pela Henna':'criado por você')+'</span></div><div class="progress"><span style="width:'+pct+'%"></span></div></div>'}).join(''):'<div class="empty">Quando um assunto começar a se repetir, a Henna pode sugerir transformá-lo em projeto.</div>'}
function renderAchievements(){var defs=unlockAchievements();byId('achievementsList').innerHTML=defs.map(function(a){var unlocked=state.achievements.indexOf(a.id)>=0;return '<div class="achievement '+(unlocked?'unlocked':'')+'"><b>'+(unlocked?'✓ ':'○ ')+esc(a.title)+'</b><p>'+esc(a.desc)+'</p></div>'}).join('')}
function renderFocusHistory(){var list=state.focusSessions.slice().reverse().slice(0,6);byId('focusHistory').innerHTML=list.length?list.map(function(s){var label=s.result==='done'?'Concluído':s.result==='partial'?'Parcial':'Não concluído';return '<div class="item"><div class="itemTop"><b>'+esc(label)+'</b><span class="time">'+new Date(s.endedAt).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})+'</span></div><p>'+esc(s.goal)+'</p></div>'}).join(''):'<div class="empty">Suas sessões de foco aparecerão aqui.</div>'}
function render(){updateProfile();var open=state.tasks.filter(function(x){return !x.done}).length,done=state.tasks.length-open;byId('sMem').textContent=state.memories.length;byId('sTasks').textContent=open;byId('sProjects').textContent=state.projects.filter(function(p){return !p.archived}).length;byId('sDone').textContent=done;byId('brandSub').textContent=state.name?'assistente de '+state.name:'seu segundo cérebro';byId('helloTitle').innerHTML=state.name?'Olá, '+esc(state.name)+'.<br><span class="grad">O que importa agora?</span>':'Sua mente,<br><span class="grad">mais leve.</span>';byId('currentName').textContent=state.name||'Não definido';byId('profileSummary').textContent=(state.profile.topics&&state.profile.topics.length)?'Temas: '+state.profile.topics.slice(0,3).join(', '):'Ainda coletando contexto.';renderBrief();renderAttention();renderConnections();renderProjects();renderAchievements();var recent=state.memories.slice().reverse().slice(0,4);byId('recentList').innerHTML=recent.length?recent.map(itemHtml).join(''):'<div class="empty">Ainda não há memórias. Capture seu primeiro pensamento acima.</div>';renderMemories();renderTasks();renderChat();renderFocusHistory();var bi=byId('briefIdea'),bn=byId('briefNext'),br=byId('briefReview');if(bi)bi.onclick=saveIdea;if(bn)bn.onclick=function(){go('assistant');ask('O que devo fazer agora?')};if(br)br.onclick=function(){go('assistant');ask('Faça meu briefing de hoje')};safeSave()}
function renderMemories(){var q=byId('searchInput').value.trim(),list=q?smartSearch(q):state.memories.slice().reverse();byId('memoryList').innerHTML=list.length?list.map(itemHtml).join(''):'<div class="empty">Nada encontrado.</div>'}
function renderTasks(){var tasks=state.tasks.slice().sort(function(a,b){if(a.done!==b.done)return a.done?1:-1;if((a.priority||'normal')!==(b.priority||'normal'))return a.priority==='high'?-1:1;return (a.created||0)-(b.created||0)});byId('taskList').innerHTML=tasks.length?tasks.map(taskHtml).join(''):'<div class="empty">Nenhuma tarefa ainda.</div>'}
function renderChat(){var arr=state.chat.length?state.chat:[{role:'ai',text:(state.name?'Oi, '+state.name+'! ':'')+'Eu sou a Henna. Posso ajudar com ideias, tarefas, decisões, memórias e padrões.'}];byId('messages').innerHTML=arr.map(function(m){return '<div class="bubble '+(m.role==='user'?'user':'aiMsg')+'">'+esc(m.text).replace(/\n/g,'<br>')+'</div>'}).join('')}
